import { useEffect, useState } from "react";
import { AssetsLoader } from "../lib";
import { SnakeGamePage } from "./game";

export function SnakeLoaderPage() {
    const [assetsLoader] = useState(() => new AssetsLoader());
    const [loaded, setLoaded] = useState(false);

    useEffect(() => {
        assetsLoader.load().then(() => {
            setLoaded(true);
        })
    }, [assetsLoader]);

    if (!loaded) {
        return (
            <div className="bg-black text-white w-full h-screen flex flex-col gap-15 items-center justify-center">

                <video src="/snake/title.webm" className="max-w-2xl w-full px-4 pointer-events-none outline-none" poster="/snake/title.png" autoPlay muted playsInline />

                <div className="flex justify-between clamp-[w,250px,400px] clamp-[h,30px,40px] px-2 py-[2px] rounded-sm overflow-hidden bg-white">
                    <div className="w-[70%] flex h-full">

                        <div className="bg-no-repeat bg-center bg-contain aspect-square  -rotate-90"
                            style={{
                                backgroundImage: "url('/snake/skins/classic/tail.png')",
                                imageRendering: "pixelated"
                            }}>

                        </div>

                        <div
                            className="h-full flex-1 bg-repeat-x bg-center bg-contain"
                            style={{
                                backgroundImage: "url('/snake/skins/classic/body-2.png')",
                                imageRendering: "pixelated"
                            }}
                        />


                        <div className="bg-no-repeat bg-center bg-contain aspect-square  rotate-90" style={{ backgroundImage: "url('/snake/skins/classic/head.png')" }}>

                        </div>
                    </div>

                    <div className="bg-no-repeat bg-center bg-contain aspect-square m-1" style={{
                        backgroundImage: "url('/snake/eatable/apple.png')",
                        imageRendering: "pixelated"

                    }}>

                    </div>
                </div>

                <div className="absolute bottom-0 py-2 px-8 font-pixel clamp-[text,sm,lg] text-center">
                    All assets are human generated by rémy.  Directed by Kadir
                </div>
            </div>
        );
    }

    return <SnakeGamePage assets_loader={assetsLoader} />
}
